### ISSUE TITLE
Can't save entry 

### ISSUE THREAD

**Issue by magicspon** [ethercreative/seo#142] opened 2018-09-24 12:16 UTC
### Description

Can't save any entries that are using the SEO field

The following error appears below the field:

`SEO should contain at most 65,535 characters.`

### Steps to reproduce

1. Save entry

### Additional info

- Craft version: 3.0.25
- SEO version: 3.4.4
- PHP version: 7.2.7
- Database driver & version: MySQL 5.7.22
- Other Plugins: CraftQL, Entry Instructions, Feed Me, ImageOptimize, Redactor

**Comment by janhenckens** [comment] 2018-11-06 14:52
@magicspon Did you fix a solution for this? We're having a same issue with a specific entry on one of our sites.

**Comment by magicspon** [comment] 2018-11-06 15:27
I did... alas I can't remember what I did... 

Have you tried turning it off and on again!

**Comment by Tam** [comment] 2018-11-06 15:29
Can you check your logs to see what data it's trying to save?

**Comment by janhenckens** [comment] 2018-11-06 15:39
Removing the images the client added to the social tab seems to fix it. Will try to reproduce

**Comment by janhenckens** [comment] 2018-11-06 15:41
Hmm, now I'm running into #133, while I'm running `3.4.4`

**Comment by janhenckens** [comment] 2018-11-07 09:58
Found what's causing this: earlier this week we added ImageOptimize from nystudio107 and the field data from those fields (4 fields in our case) is getting saved to the SEO data - more generally any field that was added to the asset is also saved here.

In this case disabling ImageOptimize's SVG placeholder was a solution since we weren't using that. 

More generally, it seems more logically to save the asset's ID and get all needed properties when rendering the seo snippet.

**Comment by janhenckens** [comment] 2018-11-20 12:18
Hey hey, any update on this?

**Comment by magicspon** [comment] 2019-01-15 15:08
This is happening again...
Latest versions:

PHP version	7.2.7
Database driver & version	MySQL 5.7.22
Image driver & version	GD 7.2.7
Craft edition & version	Craft Pro 3.0.37
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
 
CraftQL: 1.2.1
Entry Instructions: 1.0.4
1.5.1: ImageOptimize
2.1.7: Redactor
3.4.4: SEO
1.0.1: Tags


Any thoughts? news?

**Comment by janhenckens** [comment] 2019-01-21 13:19
@Tam Is this issue fixed in the latest beta?

**Closed as completed** 2019-07-25 11:48 UTC
Labels: bug
