### ISSUE TITLE
Custom URL added to Sitemap every save, can't delete

### ISSUE THREAD

**Issue by bradhardinge** [ethercreative/seo#308] opened 2020-05-29 02:52 UTC
### Description
In the Sitemap configuration, every time I hit Save, a new Custom URL is added and I can't delete them with the 'x' buttons.

![Screen Shot 2020-05-29 at 12 46 17 pm](https://user-images.githubusercontent.com/2033525/83215552-97b5ae80-a1aa-11ea-86a5-dd93f1b5c98c.png)

### Steps to reproduce

1. Standard install and setup as far as I can tell.

### Additional info

- Craft version: 3.4.20
- SEO version: 3.6.5.1
- PHP version: 7.4
- Database driver & version: MySQL (8.0)

**Comment by juban** [comment] 2020-07-03 06:36
I can confirm.
A workaround is to edit the dom and remove the custom urls table inputs before saving the configuration.
Seems the issue comes from the first hidden row of that table which is posted as values on save leading to the unwanted additional custom url.

**Comment by jakepm** [comment] 2020-09-03 12:10
Also confirmed/replicated.
Deleting the rows/inputs from the DOM on the settings page, does indeed remove the custom URLs on save.
However, the issue still persists with future saves and add/delete still doesn't work.

**Comment by masiorama** [comment] 2020-12-18 16:51
I have the same issue.

**Comment by RyanRoberts** [comment] 2021-01-19 16:32
+1 with this problem.

@juban Interesting workaround for now, thanks.

**Comment by masiorama** [comment] 2021-07-07 09:09
This seems to be fixed on https://github.com/ethercreative/seo/releases/tag/3.7.4

**Comment by alexjcollins** [comment] 2021-07-07 09:10
@masiorama Thanks for flagging - you're right!

**Closed as completed by alexjcollins** 2021-07-07 09:10 UTC
