### ISSUE TITLE
Plugin generates sitemap only for one language

### ISSUE THREAD

**Issue by harispepic** [ethercreative/seo#253] opened 2019-09-24 07:21 UTC
### Description
The plugin is currently generating a sitemap for the first site and not for the other sites.

![Bildschirmfoto 2019-09-24 um 09 15 56](https://user-images.githubusercontent.com/25743047/65489683-f1dbd280-deab-11e9-955b-fc8df1366e6b.png)

But in the settings there are all 3 languages visible

![Bildschirmfoto 2019-09-24 um 09 15 09](https://user-images.githubusercontent.com/25743047/65489627-d40e6d80-deab-11e9-9106-f5ed36e18b87.png)

Am I doing something wrong or is this a plugin bug?

### Additional info

- Craft version: 3.3.4.1
- SEO version: 3.6.2
- PHP version: 7.3.8
- Database driver & version: MySQL 5.7.26

**Comment by alexjcollins** [comment] 2019-09-24 10:18
Hi @harispepic - this is on our radar and something we'll definitely be implementing sometime in (hopefully) the near future. This is technically a duplicate of https://github.com/ethercreative/seo/issues/132 so I'm going to close this for now.

**Closed as completed by alexjcollins** 2019-09-24 10:18 UTC
