### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by christopherdowson-contrast** [ethercreative/seo#251] opened 2019-09-11 12:15 UTC
![image](https://user-images.githubusercontent.com/46570789/64696394-315ef380-d496-11e9-9981-c7a597af4151.png)

Should read "Optimisation Checklist"

**Comment by alexjcollins** [comment] 2019-09-11 12:29
Thanks (duplicate of #227 ). Will be fixed in the next release

**Closed as completed by alexjcollins** 2019-09-11 12:29 UTC
