### ISSUE TITLE
Problem with canonical

### ISSUE THREAD

**Issue by giampo1991** [ethercreative/seo#469] opened 2024-03-05 08:36 UTC
### Description
Since the last update there were problems with canonical headers. On multisites with languages ​​in the subdirectory the canons appear as "https://www.mywebsites.com/en/en/about-us". sometimes even the folder was repeated three times.

### Steps to reproduce

1.Update craft to the latest versione
2.Update SEO to the latest version

### Additional info

- Craft version:4.8.0
- SEO version:4.2.2
- PHP version:8.1

**Comment by alexjcollins** [comment] 2024-03-05 09:08
@giampo1991 Thanks for sharing—we'll take a look.

**Comment by cristiano-c1** [comment] 2024-03-18 21:18
following, same problem here, on a multisite installation

1. Craft CMS 4.8.3
2. SEO version:4.2.2
3. PHP_VERSION | 8.1.27

**Comment by fvwanja** [comment] 2024-03-19 16:09
Same here 👋 

Craft version: 4.8.1
SEO version: 4.2.2
PHP version: 8.2.0

**Comment by HarroH** [comment] 2024-04-30 13:28
Same issue here.

Craft version: `4.8.11`
SEO version: `4.2.2`
PHP version: `8.3.6`

Issue seems to come from the fix related to the pagination in the canonical link. The `getFullPath` function returns the language path included in the path and the `UrlHelper::siteUrl` already has the language path in it. So it gets a double language path on the return.

Rolled back to version `4.2.1` to fix it. Don't have enough knowledge of craft and the pagination fix (what it fixes) to come up with a solution for this. Hope someone does!

**Comment by mazaalai** [comment] 2024-05-21 10:25
Is there a solution to this problem? I have the same problem with my site.

I think that this broke the canonical.
"use pagination information on canonical (via @therealpecus)"

![image](https://github.com/ethercreative/seo/assets/15675633/e94e1509-a88b-445c-96d7-fd984ff782c2)

**Comment by therealpecus** [comment] 2024-05-21 17:59
Hi all, sorry for this nasty bug I introduced while fixing the canonical in paginated pages.

I'll take a look and revise the code so that it keeps pagination info but avoids repeating the language prefix. In the meanwhile you can downgrade to 4.2.1 as suggested (edit your `composer.json` and specify the dependency as 
```
"ether/seo": "4.2.1",
```
without the caret in front, then run `composer update`

**Comment by mateostabio** [comment] 2024-08-02 13:56
This is a serious issue. All our SEO traction we built until now has been on a slow decline for the past 2 months since the introduction to this issue.

**Comment by therealpecus** [comment] 2024-08-05 07:08
to everyone coming across this issue:
- there is a PR ready since mid-May (#480 for v4, #481 for those still on craft 2.x) that fixes the regression while keeping pagination info on canonical
- @Tam needs to approve and merge in the main code branch and make a release to npm so that updating your plugin in Craft fixes the issue

This is a free plugin, and we can't expect the maintainer to be always available. I am providing a couple of workarounds to allow everyone to adopt a fix in the meanwhile. Use **either one** depending on your familiarity with the process.

# workarounds
- downgrade to 4.2.1: run `composer require ether/seo:4.2.1` (if you use version 3.x of the plugin, use `composer require ether/seo:3.7.6`)
- alternatively, manually patch the plugin code adopting the changes in the PR: remove the red lines in `SeoData.php` and add the green lines from https://github.com/ethercreative/seo/pull/480/files . The file will be in your `vendor\ether\seo\src\models\data` folder. restart Craft to ensure changes are applied.

If you downgrade via composer, the plugin version will be pinned in your `composer.json` and composer will not try to update it. When an update is release, use `composer require ether/seo` to unpin the plugin version, or update via Craft UI.

**Comment by Baertie** [comment] 2024-09-16 12:45
Hi 
I use the latest version of craft cms 5 so i cannot downgrade to 4.2.1

Is there a workaround for that?

**Comment by Baertie** [comment] 2024-10-03 09:01
@therealpecus 
Hi
I use the latest version of craft cms 5 so i cannot downgrade to 4.2.1

Is there a workaround for that?

**Comment by therealpecus** [comment] 2024-10-03 10:58
@Baertie use the manual method per the post above:

> manually patch the plugin code adopting the changes in the PR: remove the red lines in `SeoData.php` and add the green lines from https://github.com/ethercreative/seo/pull/480/files . The file will be in your `vendor\ether\seo\src\models\data` folder. restart Craft to ensure changes are applied.

for v5 the `getCanonical` function starts at line :378

**Closed as completed** 2024-10-09 10:53 UTC
