### ISSUE TITLE
js error in BO, sitemap section

### ISSUE THREAD

**Issue by masiorama** [ethercreative/seo#325] opened 2020-09-21 09:34 UTC
### Description
If I access the sitemap section of the plugin, I get the js error "Uncaught TypeError: d.EditableTable is not a constructor".

![image](https://user-images.githubusercontent.com/731916/93752041-5edc9200-fbfe-11ea-888c-909c691621fb.png)

As a side effect (I guess), I cannot manage the custom URL section, neither delete urls nor disable.

### Additional info

- Craft version: 3.4.29.1
- SEO version: 3.6.6
- PHP version: 7.4
- Database driver & version: MySQL 5.6
- Other Plugins: Amazon S3, Disqus, Element API, MatrixMate, Redactor, SimpleSharing, Tags, Wheel Form

**Comment by masiorama** [comment] 2020-10-02 07:08
Am I the only one experiencing this issue?

**Comment by masiorama** [comment] 2020-10-19 07:05
... I guess so. Any suggestions?

**Comment by alexjcollins** [comment] 2020-10-19 07:08
@masiorama Thanks for flagging – we're able to replicate and will try and get a fix shortly.

**Comment by masiorama** [comment] 2020-11-12 10:01
Hello @alexjcollins any ETA? 
Just wondering, thanks!

**Comment by masiorama** [comment] 2020-12-16 16:48
Sorry to bother, but I still have issues with this problem, and I cannot handle the sitemap the right way. Is this still a WIP? Thanks!

**Comment by masiorama** [comment] 2021-02-19 09:52
Hello, got any updates? Thanks in advance.

**Comment by idawgik** [comment] 2021-02-24 22:51
I'm having this same issue. Unable to add custom urls, clicking the button doesn't do anything. The same Javascript error.

**Comment by jakepm** [comment] 2021-03-19 11:40
@alexjcollins @Tam - This is still an issue that we cannot get past. We really need to be able to add custom URLs for a project on a site using this plugin. Please could you provide an ETA on a fix, or at least a workaround?

**Comment by idawgik** [comment] 2021-04-05 20:03
Ok, so I did some poking around for this and think I have a work around. 

The issue is on Line 47 of the (source mapped) SeoSettings.js file there is this:

`new SeoSettings.EditableTable(`

That throws the error of not being a constructor.

If you remove the "new" from the line, everything works. So it should be:

`SeoSettings.EditableTable(`

It would be great if this could be fixed and released as an update to the plugin so modifying core plugin files wouldn't be necessary.

**Comment by masiorama** [comment] 2021-04-12 15:03
Thanks @idawgik for your workaround. 
@alexjcollins do you think what idawgik suggested is the proper way to address the issue, and could it be proposed as a PR?
Thanks to all of you!

**Comment by niektenhoopen** [comment] 2021-04-12 15:03
I can confirm that the solution of @idawgik works.

I am just not sure if something else breaks because this line is unchanged for 3 years now:
https://github.com/ethercreative/seo/blame/v3/resources/js/SeoSettings.js#L47

**Comment by niektenhoopen** [comment] 2021-04-26 15:31
@alexjcollins You said this 6 months ago:
> Thanks for flagging – we're able to replicate and will try and get a fix shortly.

Any updates on that? I can make a PR, I just need to know what needs to be done.

**Comment by niektenhoopen** [comment] 2021-05-20 10:06
@jamesedmonston @alexjcollins @Tam Guys, please let me know what I can do or let us know that this plugin is no longer maintained. There is a fix proposed (above) and we just want to know if that breaks anything else. 

I cannot use the sitemap functionality anymore. Everytime I save sitemap settings, it adds an extra empty custom URL to the sitemap. 
You are explicitly saying not to include the homepage but **that is now happening on every save** If you need more info, please contact me and I can show you the behaviour in a Teams/Meet/whatever meeting.

**Closed as completed** 2021-05-28 10:50 UTC
Labels: bug

**Comment by niektenhoopen** [comment] 2021-05-28 15:56
Thank you @Tam!
